
#\u670D\u52A1\u5668\u7AEF\u53E3
server:
  port: 8081

#\u914D\u7F6ESpring\u76F8\u5173\u4FE1\u606F
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro-test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

#\u914D\u7F6EMyBatis
mybatis:
  type-aliases-package: com.huyang.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D

#\u6253\u5370Sql\u65E5\u5FD7
logging:
  level:
    com.huyang.mapper: debug